openapi: 3.0.0
info:
  title: 'my.reMarkable API'
  description: 'Definition of the reMarkable API `https://my.remarkable.com`'
  version: 1.0.0
servers:
  - url: 'https://my.remarkable.com'
paths:
  /downloadLinks/getall:
    get:
      summary: 'Get all software download links'
      operationId: getAllDownloadLinks
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllDownloadLinksResponse'
  /token/json/2/device/new:
    post:
      summary: 'Register new device'
      tags:
        - Device
      operationId: registerNewDevice
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterNewDeviceRequest'
      responses:
        200:
          description: ''
          content:
            text/html:
              schema:
                type: string
                description: 'JWT token of the device in plain text.'
  /token/json/2/user/new:
    post:
      summary: 'Obtain access token'
      description: 'Obtains an expiring access token with the device token.'
      tags:
        - Device
      security:
        - DeviceTokenAuth: [ ]
      operationId: getAccessToken
      responses:
        200:
          description: ''
          content:
            text/html:
              schema:
                type: string
                description: 'JWT access token in plain text.'
components:
  schemas:
    RegisterNewDeviceRequest:
      type: object
      properties:
        code:
          type: string
          pattern: '^[a-z]{8}$'
          description: |
            Single-use activation token to couple new device.

            Get code from:
            * https://my.remarkable.com/connect/desktop for windows or macos
            * https://my.remarkable.com/connect/mobile for mobile devices
            * https://my.remarkable.com/connect/browser for browsers
            * https://my.remarkable.com/connect/remarkable for reMarkable devices
          example: 'abcdefgh'
        deviceDesc:
          type: string
          enum: [ 'desktop-windows', 'desktop-macos', 'desktop-linux', 'mobile-android', 'mobile-ios', 'browser-chrome', 'remarkable' ]
        deviceID:
          type: string
          description: 'UUIDv4 or reMarkable id of the device.'
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}|RM\d{3}-\d{3}-\d{5}$'
          example: '3892eb50-4697-4c72-aadc-32b766bce3c0 or RM123-456-78912'
      required:
        - code
        - deviceDesc
        - deviceID
    AllDownloadLinksResponse:
      type: object
      properties:
        Mac:
          type: string
          format: url
          example: 'https://downloads.remarkable.com/desktop/production/mac/reMarkable-2.3.1-126-a3a0129fd.dmg'
        Win:
          type: string
          format: url
          example: 'https://downloads.remarkable.com/desktop/production/win/reMarkable-2.3.2-win32.exe'
      required:
        - Mac
        - Win
  securitySchemes:
    DeviceTokenAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: 'Token obtained from device registration via `/token/json/2/device/new`.'
